### ISSUE TITLE
Travis CI build

### ISSUE THREAD

**Issue by martin-v** [retest/recheck-web-js#1]
* Build on travis
* Badge to readme
* Automatic release as [webjars](https://www.webjars.org/) on tags

**Comment by LLIu33** [comment]
> 
> 
>     * Build on travis
> 
>     * Badge to readme

done in Feature/unify js

**Comment by martin-v** [comment]
Thx for travis build.

> > * Badge to readme
> done in Feature/unify js
I didn't see the badge in the readme, fixed in #3 ;)

I will move the "Automatic release as webjars on tags" to a separate issue -> #4

**Comment by martin-v** [comment]
Done @LLIu33 thx for your work.
