### ISSUE TITLE
Automatic release as webjars on tags

### ISSUE THREAD

**Issue by martin-v** [retest/recheck-web-js#4]
We want to release for each npm release also a webjar, so that we can use it in our java projects.

**Comment by martin-v** [comment]
Some research results:

webjars.org can be create webjars from existing npm releases or npm project repos.

For npm releases the build fails with:
```
Starting Deploy
The metadata was missing a required field: /repository/url
```
@LLIu33 do you know how to set this value in the npm metadata?

----

URL to trigger directly a deployment for a npm release version 
```
https://www.webjars.org/deploy?webJarType=npm&nameOrUrlish=recheck-web-js&version=1.0.4
```

The github repo build works, but has a ugly ArtifactID
```
[...]
Synced With Maven Central
Deployed!
It will take a few hours for the Maven Central index to update but you should be able to start using the NPM WebJar shortly.
GroupID = org.webjars.npm
ArtifactID = github-com-retest-recheck-web-js-
Version = 1.0.4
```

Request to start a deployment of a github repo version
```
https://www.webjars.org/deploy?webJarType=npm&nameOrUrlish=https%3A%2F%2Fgithub.com%2Fretest%2Frecheck-web-js%2F&version=v1.0.4
```

**Comment by LLIu33** [comment]
added repository url in 
https://github.com/retest/recheck-web-js/pull/2/commits/b551b57530c6c43012444b9162057c905ed3d08c
